import { React, useEffect, useState } from "react";
import * as fs from "fs";
import Head from "next/head";
import styles from "../styles/Blog.module.css";
import Link from "next/link";

const Blog = (props) => {
  let [blogs, setBlogs] = useState(props.Data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Blogs - iCoders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 style={{ textAlign: "center" }}>Latest Blog</h1>

        <div className={styles.grid}>
          {/* <Link href={`blogpost/how-to-learn-java`} >
			  <div className={styles.card}>
            <h2>How to learn Java?</h2>
            <p>Find in-depth information about Next...</p>
			  </div>
          </Link> */}

          {blogs.map((blog, i) => {
            return (
              <Link key={i} href={`blogpost/${i + 1}`}>
                <div className={styles.card}>
                  <h2>{blog.Title}</h2>
                  <p>{blog.Content.slice(0, 70) + "..."}</p>
                </div>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps(context) {
  let mainData = [];

  let data = fs.readFileSync("DB/db.json", "utf-8");
  data = JSON.parse(data);

  let totelBlogCount = Object.keys(data).length;

  for (let i = 1; i <= totelBlogCount; i++) {
    mainData.push(data[`${i}`]);
  }

  return {
    props: {
      Data: mainData,
    },
  };
}

export default Blog;
