import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import * as fs from 'fs'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  let [blogs, setBlogs] = useState(props.Data)
  // console.log(blogs);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home - iCoders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to iCoders
        </h1>
        <div className={styles.grid}>
          {
            blogs.map((blog, i) => {
              return (
                <Link key={i} href={`blogpost/${i+1}`} >
                  <div className={styles.card}>
                    <h2>{blog.Title}</h2>
                    <p>{blog.Content.slice(0, 70)+'...'}</p>
                  </div>
                </Link>
              )
            })
        }
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <pre> Aman Programmer</pre>
      </footer>
    </div>
  )
}

export async function getStaticProps(context) {
  let mainData = [];

  let data = fs.readFileSync("DB/db.json", "utf-8");
	data = JSON.parse(data);

  let totelBlogCount = Object.keys(data).length;

  for (let i=1; i<=totelBlogCount; i++){
    mainData.push(data[`${i}`]);
  }
  
  return {
    props: {
      Data: mainData
    } 
  }
}