import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - iCoders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to iCoders
        </h1>

        <h2 className={styles.heading2}>RECENT BLOGS</h2>
        <div className={styles.grid}>

          <div className={styles.card}>
            <h2>How to learn Java?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Python?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn JavaScript?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Java?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Python?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn JavaScript?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Java?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Python?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn JavaScript?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Java?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn Python?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          <div className={styles.card}>
            <h2>How to learn JavaScript?</h2>
            <p>Find in-depth information about Next...</p>
          </div>

          
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by{' '}
          <pre> Aman Programmer</pre>
      </footer>
    </div>
  )
}
